# Generated by Django 5.2.9 on 2025-12-24 10:13

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la catégorie')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Slug URL')),
                ('icon', models.CharField(blank=True, help_text="Emoji ou classe d'icône", max_length=50, verbose_name='Icône')),
                ('color', models.CharField(default='text-primary', help_text='Classe Tailwind (ex: text-primary, text-red-500)', max_length=50, verbose_name='Couleur')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('icon', models.CharField(blank=True, help_text="Classe d'icône ou emoji", max_length=50)),
                ('color', models.CharField(default='text-primary', help_text='Classe Tailwind', max_length=50)),
            ],
            options={
                'verbose_name': 'Technologie',
                'verbose_name_plural': 'Technologies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du projet')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug URL')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Sous-titre court')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='projects/%Y/%m/', verbose_name='Image principale')),
                ('gallery_images', models.JSONField(blank=True, default=list, help_text="Liste d'images supplémentaires (JSON)", verbose_name="Galerie d'images")),
                ('description', models.TextField(verbose_name='Description courte (pour cards)')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Contenu complet avec éditeur WYSIWYG', verbose_name='Description détaillée')),
                ('client', models.CharField(blank=True, max_length=200, verbose_name='Client')),
                ('year', models.PositiveIntegerField(verbose_name='Année de réalisation')),
                ('duration', models.CharField(blank=True, help_text="Ex: '3 mois', '6 semaines'", max_length=100, verbose_name='Durée du projet')),
                ('live_url', models.URLField(blank=True, verbose_name='Lien vers le site live')),
                ('github_url', models.URLField(blank=True, verbose_name='Lien GitHub')),
                ('demo_url', models.URLField(blank=True, verbose_name='Lien démo/vidéo')),
                ('meta_description', models.TextField(blank=True, help_text='Description pour moteurs de recherche (160 caractères max)', max_length=160, verbose_name='Meta Description')),
                ('is_featured', models.BooleanField(default=False, help_text="Afficher sur la page d'accueil", verbose_name='Projet mis en avant')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
                ('order', models.IntegerField(default=0, help_text="Ordre d'affichage (0 = premier)", verbose_name='Ordre')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de vues')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='portfolio.category', verbose_name='Catégorie')),
                ('technologies', models.ManyToManyField(blank=True, related_name='projects', to='portfolio.technology', verbose_name='Technologies utilisées')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['slug'], name='portfolio_p_slug_e96b08_idx'), models.Index(fields=['is_published', 'order'], name='portfolio_p_is_publ_5064b5_idx')],
            },
        ),
    ]
